# register user

POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json

{
  "username": "exampleUser",
  "email": "example@example.com",
  "password": "examplePassword"
}


###

# login user

POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "exampleUser",
  "password": "examplePassword"
}

###

# Only bbox
GET http://localhost:8000/api/chargers?northEast_latitude=50.0&northEast_longitude=20.0&southWest_latitude=49.0&southWest_longitude=19.0

###

# bbox + min power 
GET http://127.0.0.1:8000/api/chargers/?northEast_latitude=50.0&northEast_longitude=20.0&southWest_latitude=49.0&southWest_longitude=19.0&min_power=50

###

# bbox + power range

GET http://127.0.0.1:8000/api/chargers/?northEast_latitude=50.0&northEast_longitude=20.0&southWest_latitude=49.0&southWest_longitude=19.0&min_power=50&max_power=100

###

# bbox + two connector types

GET http://127.0.0.1:8000/api/chargers/?northEast_latitude=50.0&northEast_longitude=20.0&southWest_latitude=49.0&southWest_longitude=19.0&connector_type=Chademo, IEC62196Type2CCS


###

# all

GET http://127.0.0.1:8000/api/chargers/?northEast_latitude=50.0&northEast_longitude=20.0&southWest_latitude=49.0&southWest_longitude=19.0&min_power=50&max_power=100&connector_type=Chademo


###

# add to favorites

POST http://127.0.0.1:8000/api/favorites/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleGFtcGxlVXNlciIsImV4cCI6MTczMzQ5MTk4M30.xgz9OScGBQHgxgoU1aFnk1uv1kqodeuaLbkIA6L5sv0

{
  "charger_id": 124
}


###

# get favorites

GET http://127.0.0.1:8000/api/favorites/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleGFtcGxlVXNlciIsImV4cCI6MTczMzQ5MTk4M30.xgz9OScGBQHgxgoU1aFnk1uv1kqodeuaLbkIA6L5sv0

###

# remove from favorites

DELETE http://127.0.0.1:8000/api/favorites/?charger_id=123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJleGFtcGxlVXNlciIsImV4cCI6MTczMzQ5MTk4M30.xgz9OScGBQHgxgoU1aFnk1uv1kqodeuaLbkIA6L5sv0


###

# get charging availability

GET http://127.0.0.1:8000/api/charging-status/1
